/**
 * "Best X in London" pages — targeting commercial investigation keywords.
 * These capture "am I choosing the right agency" searches.
 * Position Meridian in a curated list format with honest analysis.
 */

export type BestPage = {
  slug: string;
  service: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  image: string;
  intro: string;
  /** What to look for when choosing */
  criteria: Array<{ title: string; description: string }>;
  /** Why Meridian for this service */
  whyMeridian: string[];
  /** Market context */
  marketContext: string;
  faqs: Array<{ q: string; a: string }>;
};

export const BEST_PAGES: BestPage[] = [
  {
    slug: 'seo-agency', service: 'SEO',
    title: 'Best SEO Agency London 2026: How to Choose',
    metaTitle: 'Best SEO Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best SEO agency in London. What to look for, questions to ask, pricing comparison, and what separates good from great.',
    keywords: ['best seo agency london', 'top seo agency london', 'seo agency london reviews'],
    image: 'seo-search-optimisation',
    intro: 'There are 500+ SEO agencies in London. Most will waste your budget. Here\'s how to find the ones that won\'t — and what separates a good agency from a great one.',
    criteria: [
      { title: 'Revenue attribution, not just rankings', description: 'The best agencies report on leads and revenue generated by organic traffic — not just keyword positions. Ask for case studies with actual revenue numbers.' },
      { title: 'GEO/AEO capability', description: 'In 2026, 25-35% of commercial queries show AI Overviews. The best agencies engineer content to be cited by Google AI, ChatGPT, and Perplexity — not just ranked.' },
      { title: 'Technical depth', description: 'Core Web Vitals, schema markup, crawl budget, JavaScript rendering — the best agencies have genuine technical SEO engineers, not just content writers who call themselves "SEO specialists".' },
      { title: 'Content quality', description: 'Ask to see actual content they\'ve produced. Is it original, expert-level, cited by authoritative sources? Or is it generic 500-word blog posts that could be written by anyone?' },
      { title: 'Transparent pricing', description: 'The best agencies publish their pricing. Agencies that require "contact for a quote" on basic retainers are either overpriced or inconsistent.' },
      { title: 'Client retention above 80%', description: 'Ask for their 12-month and 24-month retention rates. Below 70% at 12 months means clients are leaving — that tells you everything about results quality.' },
    ],
    whyMeridian: [
      '94% client retention at 24 months — highest published rate of any London SEO agency',
      '+342% average organic traffic uplift across all clients in 12 months',
      'AI Overview and ChatGPT citation engineering included in every retainer',
      'Transparent pricing published on every page — 40% below London market average',
      'Revenue attribution dashboards, not vanity traffic reports',
      'Dedicated senior account lead on every engagement (not junior rotation)',
    ],
    marketContext: 'The London SEO agency market is one of the most competitive in the world. Average retainer costs run £2,500-£5,800/month for Growth-tier work. CPCs on SEO-related keywords themselves hit £14-£28. There are roughly 500 agencies claiming to do SEO in London, but fewer than 50 have the technical depth and content capability to compete on hero terms.',
    faqs: [
      { q: 'Who is the best SEO agency in London?', a: 'The best agency depends on your industry, budget, and goals. Look for: published retention rates above 80%, revenue attribution (not just traffic), GEO/AEO capability, and transparent pricing. Meridian scores highly on all four.' },
      { q: 'How much does the best SEO cost in London?', a: 'Quality SEO in London costs £1,200-£5,800/month. Below £1,000/month typically means junior-only teams and generic content. Meridian\'s Growth tier delivers enterprise-level scope at £1,490/month — 40% below the market average.' },
      { q: 'How do I verify an SEO agency\'s claims?', a: 'Ask for: named case studies with revenue numbers, their own site\'s Core Web Vitals scores, 12-month client retention rate, and references from clients in your industry. Run their site through PageSpeed Insights — if their own site is slow, walk away.' },
    ],
  },
  {
    slug: 'web-design', service: 'Web Design',
    title: 'Best Web Design Agency London 2026: How to Choose',
    metaTitle: 'Best Web Design Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best web design agency in London. Portfolio review tips, pricing, platform comparison, and what makes a great website in 2026.',
    keywords: ['best web design london', 'top web design agencies london', 'web design agency london reviews'],
    image: 'ux-ui-design',
    intro: 'A great web design agency builds sites that convert visitors into customers. A mediocre one builds pretty sites nobody visits. Here\'s how to tell the difference.',
    criteria: [
      { title: 'Performance obsession', description: 'The best agencies treat Core Web Vitals (LCP < 2.5s, INP < 200ms, CLS < 0.1) as contractual requirements, not aspirational targets. Run their portfolio through PageSpeed Insights.' },
      { title: 'Conversion engineering', description: 'Pretty design is table stakes. The best agencies use heatmaps, scroll maps, A/B testing, and conversion rate data to engineer sites that actually generate leads and sales.' },
      { title: 'Platform flexibility', description: 'Beware agencies that only build on one platform. The best recommend Webflow, Next.js, Shopify, or WordPress based on your needs — not what they prefer to build in.' },
      { title: 'SEO built in', description: 'Schema markup, responsive images (AVIF/WebP), clean URL structure, and AI Overview optimisation should be standard — not a £2,000 add-on.' },
      { title: 'You own everything', description: 'Domain, hosting, CMS login, code repository, analytics accounts. Any agency that builds on their infrastructure is creating lock-in.' },
      { title: 'Post-launch support included', description: 'The first 30 days after launch always require tweaks. The best agencies include a post-launch support window at no extra cost.' },
    ],
    whyMeridian: [
      'Every site ships with LCP under 2.5s — contractually guaranteed',
      'AVIF + WebP responsive images standard (90%+ payload reduction)',
      'Schema.org structured data baked in — Service, FAQPage, BreadcrumbList, Product',
      'Platform-agnostic: Next.js, Webflow, Shopify, WordPress — chosen on the merits',
      '40% below London market average: from £1,950 (Lite) to £14,990 (Custom)',
      '30-day post-launch support and CMS training included',
    ],
    marketContext: 'London has over 2,000 web design agencies ranging from solo freelancers to 200-person studios. Average project costs run £8,000-£25,000 for a 10-15 page site. The market is fragmented — quality varies enormously. The best indicator of quality is the agency\'s own site performance.',
    faqs: [
      { q: 'What makes the best web design agency?', a: 'Three things: performance (fast load times), conversion engineering (sites that generate leads), and SEO built in (not as an add-on). Check their own site\'s PageSpeed score first.' },
      { q: 'How much does the best web design cost in London?', a: 'Quality web design: £4,990-£15,000 for most SME sites. Below £3,000 usually means templates with minimal customisation. Meridian starts at £1,950 (Lite) with full SEO and performance optimisation.' },
      { q: 'Should I use a freelancer or agency for web design?', a: 'Agency for sites above £5,000 where SEO, performance, and ongoing support matter. Freelancer for simple brochure sites under £3,000 where you have clear requirements.' },
    ],
  },
  {
    slug: 'ppc-agency', service: 'PPC',
    title: 'Best PPC Agency London 2026: How to Choose',
    metaTitle: 'Best PPC Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best PPC agency in London. Account ownership, ROAS reporting, architecture review, and what to expect from Google Ads management.',
    keywords: ['best ppc agency london', 'top google ads agency london', 'ppc agency london reviews'],
    image: 'digital-marketing-team',
    intro: 'London PPC is the most expensive auction in the UK. The difference between a good and bad agency is tens of thousands of pounds per quarter. Here\'s how to choose.',
    criteria: [
      { title: 'Account architecture expertise', description: 'The biggest lever in PPC isn\'t bid management — it\'s campaign structure. The best agencies audit and rebuild account architecture before touching bids.' },
      { title: 'You own the accounts', description: 'You must own your Google Ads and Meta accounts. Agencies that insist on owning them are creating lock-in. Walk away from any that don\'t agree immediately.' },
      { title: 'ROAS and CPL reporting', description: 'Impressions and clicks are vanity metrics. The best agencies report on cost per lead, customer acquisition cost, and return on ad spend — tied to revenue.' },
      { title: 'Landing page CRO included', description: 'Most PPC waste comes from bad landing pages, not bad bids. The best agencies include landing page optimisation — often higher leverage than bid management.' },
      { title: 'Server-side tracking', description: 'In 2026, browser-side tracking misses 30-40% of conversions due to iOS restrictions and ad blockers. The best agencies set up Conversions API and server-side tracking.' },
      { title: 'No percentage-of-spend pricing', description: 'Percentage-of-spend incentivises the agency to increase your budget, not your efficiency. The best agencies charge flat management fees.' },
    ],
    whyMeridian: [
      'Flat management fees — not percentage of ad spend',
      'Account architecture review in week 1 (the biggest lever)',
      'You always own all ad accounts with full admin access',
      'Server-side tracking + Conversions API setup as standard',
      'Landing page CRO sprints included in Growth and Scale tiers',
      'From £390/month — 40% below the London agency average',
    ],
    marketContext: 'London PPC agencies manage some of the most expensive auctions in the world. Hero-term CPCs for service keywords hit £18-£35. There are roughly 200 agencies specialising in PPC management, with management fees ranging from £390 to £4,150/month. The agencies that focus on account architecture consistently outperform those that focus on bid management alone.',
    faqs: [
      { q: 'Who is the best PPC agency in London?', a: 'Look for: flat fees (not percentage of spend), account architecture expertise, you own the accounts, ROAS reporting (not impressions), and landing page CRO included. Meridian checks all five boxes.' },
      { q: 'How much does PPC management cost in London?', a: 'Management fees: £390-£4,150/month depending on platform count and ad spend volume. Plus ad spend: minimum £2,000-£4,000/month for competitive London terms.' },
      { q: 'Should I manage Google Ads myself?', a: 'Only if you have 10+ hours per week to dedicate. Google Ads rewards daily attention. Most businesses get better ROI with an agency because the cost savings from professional management exceed the management fee.' },
    ],
  },
  {
    slug: 'marketing-agency', service: 'Digital Marketing',
    title: 'Best Digital Marketing Agency London 2026: How to Choose',
    metaTitle: 'Best Digital Marketing Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best digital marketing agency in London. Full-service vs specialist, pricing, what to expect, and red flags to avoid.',
    keywords: ['best marketing agency london', 'best digital marketing agency london', 'top marketing agencies london'],
    image: 'digital-marketing-team',
    intro: 'London has 4,000+ digital marketing agencies. Most are generalists who do everything adequately and nothing exceptionally. Here\'s how to find the exceptions.',
    criteria: [
      { title: 'Depth over breadth', description: 'The best agencies have genuine specialists in each discipline — not account managers who "do a bit of everything". Ask who specifically will work on your SEO, PPC, and content.' },
      { title: 'Published case studies with revenue', description: 'Traffic graphs aren\'t results. The best agencies show: revenue attributed to marketing, cost per lead trends, client retention rates, and before/after comparisons.' },
      { title: 'Transparent, published pricing', description: 'Agencies that hide pricing are either expensive or inconsistent. The best publish their rates and let you compare. Secret pricing protects the agency, not you.' },
      { title: 'AI and GEO capability', description: 'In 2026, any agency that doesn\'t mention AI Overviews, ChatGPT citations, or GEO is already 18 months behind. This isn\'t a nice-to-have — it\'s core SEO strategy.' },
      { title: 'No long lock-in contracts', description: '12-month minimums protect the agency. 90-day minimums are fair — enough time to prove results, short enough to leave if they don\'t deliver.' },
      { title: 'They practise what they preach', description: 'Run the agency\'s own website through PageSpeed Insights. Check if they rank for their own keywords. If their marketing doesn\'t work for themselves, it won\'t work for you.' },
    ],
    whyMeridian: [
      '7 specialist disciplines under one roof — each with dedicated senior staff',
      '94% client retention at 24 months — published and verifiable',
      'Transparent pricing on every page — 40% below London market average',
      'AI Overview and ChatGPT citation engineering included as standard',
      '90-day minimum commitment then month-to-month — no lock-in',
      'Our own site scores 95+ on Lighthouse across all categories',
    ],
    marketContext: 'The London digital marketing agency market is the most competitive in the UK, with over 4,000 agencies competing for attention. Average retainer costs range from £2,500-£15,000/month for full-service marketing. The market is heavily consolidated at the top (large networks) and fragmented at the bottom (2-5 person shops). The sweet spot is mid-market boutique agencies with 15-50 staff who combine depth of expertise with senior-level attention.',
    faqs: [
      { q: 'What makes the best marketing agency in London?', a: 'Specialist depth in each channel, published retention rates, transparent pricing, AI/GEO capability, and no lock-in contracts. Run their own site through Lighthouse.' },
      { q: 'How much does a marketing agency cost in London?', a: 'Full-service retainers: £2,500-£15,000/month. Single-channel: £490-£5,800/month. Meridian offers full-service from £2,500/month — 40% below market.' },
      { q: 'Agency vs in-house marketing team?', a: 'In-house for £100k+/year salary costs, an agency gives you 5-7 specialists for the same budget. Most London businesses get better results with agency + fractional CMO than a small in-house team.' },
    ],
  },
  {
    slug: 'social-media-agency', service: 'Social Media',
    title: 'Best Social Media Agency London 2026: How to Choose',
    metaTitle: 'Best Social Media Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best social media agency in London. Content quality, platform expertise, reporting, and what to expect from management.',
    keywords: ['best social media agency london', 'top social media agency london', 'social media management london reviews'],
    image: 'social-media-management',
    intro: 'Most social media agencies post generic content and report on follower count. The best ones produce original creative and report on leads and revenue. Here\'s the difference.',
    criteria: [
      { title: 'In-house content production', description: 'The best agencies produce photography, video, and motion design in-house. Agencies that outsource to freelance creators deliver inconsistent quality.' },
      { title: 'Platform-specific strategy', description: 'Instagram, TikTok, LinkedIn, and X require fundamentally different strategies. Beware agencies that post the same content across all platforms.' },
      { title: 'Engagement over followers', description: 'Follower count is a vanity metric. The best agencies optimise for saves, DMs, and website clicks — the signals that actually drive business.' },
      { title: 'Paid social integration', description: 'Organic reach is declining. The best agencies combine organic content with paid amplification — Meta Ads, LinkedIn Ads, TikTok Ads — for measurable ROI.' },
      { title: 'Reporting on business outcomes', description: 'Impressions and reach don\'t pay bills. The best agencies attribute website traffic, leads, and revenue to social activity.' },
      { title: 'Real community management', description: 'Responding to comments and DMs within 1 hour during business hours. The best agencies treat social as a two-way conversation, not a broadcast channel.' },
    ],
    whyMeridian: [
      'In-house photography, video, and motion design — not outsourced',
      'Platform-specific strategy — we don\'t cross-post the same content',
      'Paid social management included in Growth and Scale tiers',
      'LinkedIn founder ghostwriting for B2B clients (8 posts/month)',
      'Business outcome reporting — leads and revenue, not just impressions',
      'From £490/month — 40% below London agency average',
    ],
    marketContext: 'The London social media management market ranges from £490-£5,800/month. There are hundreds of agencies, but most rely on stock content and scheduling tools. The agencies that produce original video content in-house consistently outperform. Instagram Reels and TikTok now account for 60%+ of reach — agencies that can\'t produce short-form video are already behind.',
    faqs: [
      { q: 'Who is the best social media agency in London?', a: 'Look for: in-house content production (especially video), platform-specific strategy, paid social integration, and business outcome reporting. Meridian offers all four.' },
      { q: 'How much does social media management cost in London?', a: 'Starter (1 platform): £490-£820/month. Growth (2 platforms + video): £1,490-£2,500/month. Scale (4 platforms + influencer): £3,490-£5,800/month.' },
      { q: 'Do I need a social media agency?', a: 'If you can\'t produce 4-5 quality Reels per week in-house, yes. The algorithm rewards consistent, high-quality original content — that\'s hard to maintain without dedicated resources.' },
    ],
  },
  {
    slug: 'branding-agency', service: 'Branding',
    title: 'Best Branding Agency London 2026: How to Choose',
    metaTitle: 'Best Branding Agency London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best branding agency in London. Strategy depth, portfolio quality, process, and what separates a logo shop from a brand builder.',
    keywords: ['best branding agency london', 'top branding agencies london', 'branding agency london reviews'],
    image: 'branding-strategy',
    intro: 'A logo shop gives you a mark. A brand agency gives you a position in the market. Here\'s how to tell the difference — and what to look for in London\'s crowded branding market.',
    criteria: [
      { title: 'Strategy before design', description: 'The best agencies start with positioning, audience, and narrative — not Illustrator. If they jump straight to logo concepts without understanding your market position, they\'re a logo shop.' },
      { title: 'Portfolio shows range', description: 'Look for variety across industries. An agency that\'s only done tech startups may not understand luxury, healthcare, or F&B. The best agencies adapt their visual language to the client.' },
      { title: 'Comprehensive guidelines', description: 'A logo file isn\'t branding. The best agencies deliver 40-80 page brand guidelines covering: logo usage, colour, typography, photography direction, tone of voice, and application examples.' },
      { title: 'They challenge your brief', description: 'The best agencies push back on bad briefs. If they agree with everything you say, they\'re order-takers, not brand builders.' },
      { title: 'Implementation support', description: 'Building the brand book is 40% of the work. Rolling it out across website, marketing, packaging, and internal communications is the other 60%. The best agencies support both.' },
      { title: 'Trademark awareness', description: 'The best agencies check trademark availability before presenting final concepts and can recommend IP lawyers for registration.' },
    ],
    whyMeridian: [
      'Strategy-first process — positioning and audience before any design work',
      'Full identity systems: logo, colour, typography, photography, motion, tone of voice',
      'Comprehensive brand guidelines (40-80 page PDF depending on tier)',
      'Trademark search support and domain advisory included',
      'Implementation support across website, marketing, and internal communications',
      'From £1,990 (Sprint) to £14,990 (Rebrand) — 40% below London agency average',
    ],
    marketContext: 'London\'s branding market is the largest in Europe with over 800 agencies ranging from solo designers to global networks. Project costs range from £2,000 for a basic identity to £100,000+ for enterprise rebrands. The key differentiator is strategy depth — the best agencies spend 40% of project time on research and positioning before any design work begins.',
    faqs: [
      { q: 'What makes the best branding agency?', a: 'Strategy before design, comprehensive guidelines (not just a logo file), trademark awareness, and implementation support. The portfolio should show range across industries.' },
      { q: 'How much does branding cost in London?', a: 'Sprint (logo + basics): £1,990-£3,500. Full identity: £4,990-£8,500. Enterprise rebrand: £14,990-£25,000+. Meridian prices 40% below market.' },
      { q: 'Do I need a rebrand or just a refresh?', a: 'Refresh if your positioning is right but the design is dated. Rebrand if your market position, audience, or business model has fundamentally changed.' },
    ],
  },
  {
    slug: 'app-developer', service: 'App Development',
    title: 'Best App Developer London 2026: How to Choose',
    metaTitle: 'Best App Developer London 2026 | Expert Guide | Meridian',
    metaDescription: 'How to find the best app developer in London. Technical vetting, portfolio review, compliance, pricing, and what to expect from a London development agency.',
    keywords: ['best app developers london', 'top app development company london', 'app developer london reviews'],
    image: 'web-hosting-domain',
    intro: 'London has 4,000+ app companies. Most will take 6 months to ship what should take 12 weeks. Here\'s how to find the ones that actually deliver.',
    criteria: [
      { title: 'Shipped apps, not wireframes', description: 'Ask for links to live apps in the App Store and Play Store. Check ratings, download counts, and crash-free rates. Wireframes and Figma mockups aren\'t evidence of shipping capability.' },
      { title: 'Platform expertise', description: 'The best agencies have genuine expertise in their recommended platform (Flutter, React Native, Swift, Kotlin) — not just theoretical knowledge. Ask about their last 5 shipped apps and what stack they used.' },
      { title: 'Compliance capability', description: 'For fintech (FCA, PCI-DSS), healthcare (NHS DSP), or regulated industries — ask for evidence of compliance experience, not just claims. Certifications (ISO 27001, Cyber Essentials) matter.' },
      { title: 'Fixed-scope, not time-and-materials', description: 'T&M billing incentivises scope creep. The best agencies quote fixed prices after a paid discovery week. If they can\'t give you a fixed price after understanding your requirements, they don\'t understand them well enough.' },
      { title: 'You own the code', description: 'Source code in your GitHub org from day one. Apple Developer and Google Play accounts in your name. If you part ways, you keep everything functional.' },
      { title: 'Post-launch support plan', description: 'Apps require ongoing maintenance: OS updates, security patches, bug fixes, feature iterations. The best agencies offer care plans and growth retainers.' },
    ],
    whyMeridian: [
      '47 apps shipped to App Store + Play Store since 2018',
      '94% first-time App Store approval rate',
      'FCA, PCI-DSS, NHS DSP compliance experience',
      'Fixed-scope pricing after paid 1-week discovery',
      'You own the code, accounts, and all work product from day one',
      'From £9,990 (MVP Lite) to £49,950 (Platform) — 40% below market',
    ],
    marketContext: 'London\'s app development market is one of the densest in the world with 4,000+ companies. Typical costs: MVP £25,000-£60,000, production app £60,000-£150,000, complex platform £150,000+. The biggest risk is agencies that overpromise timelines — a 12-week MVP quoted at 6 weeks always ends up being 16 weeks. Fixed-scope pricing with weekly demos is the best protection.',
    faqs: [
      { q: 'Who is the best app developer in London?', a: 'Check: live apps in the stores (not just mockups), platform expertise, compliance experience if needed, fixed-scope pricing, and you own the code. Meridian has shipped 47 apps with 94% first-time approval.' },
      { q: 'How much does app development cost in London?', a: 'MVP Lite: £9,990-£17,000. Full MVP: £24,990-£42,000. Enterprise platform: £49,950-£133,000+. Meridian prices 40% below market.' },
      { q: 'Flutter or React Native?', a: 'Flutter for most new MVPs — better UI control, identical cross-platform output. React Native if your team is JavaScript-first. Native (Swift/Kotlin) only if you need 60fps or deep platform APIs.' },
    ],
  },
];

export const ALL_BEST_SLUGS = BEST_PAGES.map(b => b.slug);

export function getBestPage(slug: string): BestPage | undefined {
  return BEST_PAGES.find(b => b.slug === slug);
}
