/**
 * All 32 London boroughs + the City of London.
 * Used to programmatically generate borough landing pages.
 *
 * Each borough page targets the long-tail "[service] [borough]" keyword
 * pattern (e.g. "web design shoreditch"). KD typically 15–35 vs 50+
 * for "[service] london" terms.
 */

export type Borough = {
  slug: string;
  name: string;
  postcodes: string[];
  hub: string;            // primary commercial focus
  industries: string[];
  tagline: string;        // short SEO meta
  intro: string;          // longer copy for the H1 area
  featured: boolean;      // shown in hero borough chip-set
};

export const BOROUGHS: Borough[] = [
  { slug:'shoreditch', name:"Shoreditch", postcodes:["EC2A","E1","E2"], hub:"Tech & startup", industries:["Fintech","SaaS","Crypto","Creative"], tagline:"London's startup capital", intro:"Shoreditch is the heart of London's startup scene — Silicon Roundabout, scale-up venture, and the densest cluster of fintech in Europe. We help Shoreditch businesses ship faster and rank higher.", featured:true },
  { slug:'mayfair', name:"Mayfair", postcodes:["W1J","W1K","W1S"], hub:"Finance & luxury", industries:["Private equity","Hedge funds","Luxury retail","Art"], tagline:"Premium positioning for Mayfair brands", intro:"Mayfair brands need digital that matches their physical presence. We build refined, conversion-engineered websites and discreet performance marketing for London's most premium addresses.", featured:true },
  { slug:'canary-wharf', name:"Canary Wharf", postcodes:["E14"], hub:"Financial services", industries:["Banking","Asset management","Insurance","B2B"], tagline:"Enterprise digital for the Wharf", intro:"Canary Wharf is built on enterprise-scale finance. We deliver compliant, high-performing digital programmes for the financial institutions and B2B service firms headquartered there.", featured:true },
  { slug:'kings-cross', name:"King's Cross", postcodes:["N1C"], hub:"Tech & deeptech", industries:["AI","Deeptech","Media","Healthtech"], tagline:"Where Google London meets the deeptech belt", intro:"King's Cross has become London's deeptech corridor — Google's HQ, the Crick Institute, the Knowledge Quarter. We work with the AI, healthtech and media businesses building the city's next decade.", featured:true },
  { slug:'soho', name:"Soho", postcodes:["W1D","W1F"], hub:"Creative & media", industries:["Advertising","Production","Hospitality","Tech"], tagline:"Creative London's HQ", intro:"Soho's creative density is unmatched. Our clients here include production houses, advertising agencies, post-production studios, and the bars and restaurants that feed them.", featured:true },
  { slug:'camden', name:"Camden", postcodes:["NW1"], hub:"Music, retail, scale-ups", industries:["Music","Hospitality","Retail","Tech"], tagline:"From Camden Market to Camden tech", intro:"Camden combines a world-famous market with a serious scale-up scene. We work with the lifestyle brands, music tech companies, and hospitality operators that make Camden distinctive.", featured:false },
  { slug:'hackney', name:"Hackney", postcodes:["E5","E8","E9"], hub:"Lifestyle, e-commerce", industries:["E-commerce","Hospitality","Creative","Wellness"], tagline:"East London's lifestyle engine", intro:"Hackney is where London's most interesting lifestyle brands are built. Cold brew, sneakers, indie fashion, restaurants. We build their digital presence and performance.", featured:false },
  { slug:'islington', name:"Islington", postcodes:["N1"], hub:"Indie brands, hospitality", industries:["Hospitality","Retail","Professional services"], tagline:"Indie, considered, premium", intro:"Islington's mix of independent retail, restaurants and professional services demands digital marketing with taste. We bring it.", featured:false },
  { slug:'hammersmith', name:"Hammersmith", postcodes:["W6"], hub:"West London corporate", industries:["Media","Healthcare","Tech","Hospitality"], tagline:"West London's corporate spine", intro:"Hammersmith is home to Disney, GSK Consumer Health, L'Oreal and dozens of mid-market businesses. We support their digital programmes from brand to performance.", featured:false },
  { slug:'chiswick', name:"Chiswick", postcodes:["W4"], hub:"Affluent SME", industries:["Professional services","Property","Hospitality"], tagline:"West London affluent SME hub", intro:"Chiswick's affluent SME base needs digital that converts. We deliver the full mix — local SEO, paid, social, content — to professional services, hospitality and property businesses across W4.", featured:false },
  { slug:'kensington', name:"Kensington", postcodes:["W8","SW7"], hub:"Luxury retail, museums", industries:["Luxury","Retail","Hospitality","Cultural"], tagline:"Refined digital for Kensington brands", intro:"Kensington's luxury and cultural institutions deserve digital that respects their heritage. We build it.", featured:false },
  { slug:'chelsea', name:"Chelsea", postcodes:["SW3","SW10"], hub:"Luxury, fashion, retail", industries:["Fashion","Beauty","Hospitality","Property"], tagline:"Premium positioning, SW3", intro:"Chelsea retail, restaurants and lifestyle brands need digital marketing with the same polish as their stores. We deliver it.", featured:false },
  { slug:'notting-hill', name:"Notting Hill", postcodes:["W11"], hub:"Indie creative, hospitality", industries:["Hospitality","Retail","Creative","Property"], tagline:"Independent W11 brands", intro:"Notting Hill's mix of independent retail, restaurants and creative businesses needs distinctive digital. We bring point-of-view to the work.", featured:false },
  { slug:'paddington', name:"Paddington", postcodes:["W2"], hub:"Hospitality, transport", industries:["Hospitality","Healthcare","B2B"], tagline:"W2 commercial hub", intro:"Paddington's mix of hospitality, healthcare and B2B services around the station and basin needs reliable, performance-focused digital. We deliver.", featured:false },
  { slug:'marylebone', name:"Marylebone", postcodes:["W1U","NW1"], hub:"Healthcare, professional", industries:["Healthcare","Legal","Property","Hospitality"], tagline:"Harley Street and the W1 professional class", intro:"Marylebone's clinics, chambers, professional services firms and restaurants need digital marketing that respects their positioning. We provide it.", featured:false },
  { slug:'fitzrovia', name:"Fitzrovia", postcodes:["W1T","W1W"], hub:"Media, advertising, tech", industries:["Advertising","Media","Tech","Healthcare"], tagline:"Charlotte Street and the agency belt", intro:"Fitzrovia's media, advertising and tech businesses sit at London's centre — and our work for them puts them at search's centre.", featured:false },
  { slug:'bloomsbury', name:"Bloomsbury", postcodes:["WC1A","WC1B"], hub:"Education, publishing", industries:["Education","Publishing","Healthcare","Cultural"], tagline:"WC1's intellectual quarter", intro:"Bloomsbury's universities, publishers and museums deserve digital that's as substantive as their work. We build it.", featured:false },
  { slug:'holborn', name:"Holborn", postcodes:["WC1V","WC2A"], hub:"Legal, professional", industries:["Legal","Professional services","Tech"], tagline:"Mid-town London's legal heart", intro:"Holborn's law firms, barristers' chambers and professional services firms need search visibility on terms with extreme commercial intent. Our specialist legal SEO playbook delivers.", featured:false },
  { slug:'clerkenwell', name:"Clerkenwell", postcodes:["EC1M","EC1R"], hub:"Design, architecture", industries:["Design","Architecture","Tech","Hospitality"], tagline:"London's design district", intro:"Clerkenwell's architects, designers and design-led businesses need digital that matches their craft. We deliver it.", featured:false },
  { slug:'farringdon', name:"Farringdon", postcodes:["EC1A","EC1N"], hub:"Tech, design, finance", industries:["Tech","Fintech","Design","Hospitality"], tagline:"EC1's tech and design corridor", intro:"Farringdon's tech businesses, design studios and Crossrail-driven hospitality scene need digital marketing with the same precision as the Elizabeth line. We provide it.", featured:false },
  { slug:'stratford', name:"Stratford", postcodes:["E15","E20"], hub:"E-commerce, retail, tech", industries:["E-commerce","Retail","Hospitality","Sport"], tagline:"East London's commercial engine", intro:"Stratford's Westfield-anchored economy and East Bank cultural district make it one of London's fastest-growing commercial zones. We help businesses ride the growth.", featured:false },
  { slug:'greenwich', name:"Greenwich", postcodes:["SE10"], hub:"Tourism, hospitality, tech", industries:["Hospitality","Tourism","Tech","Maritime"], tagline:"Where SE London meets the world", intro:"Greenwich combines royal heritage, world-class tourism and a growing tech base around the peninsula. We deliver digital across the spectrum.", featured:false },
  { slug:'wimbledon', name:"Wimbledon", postcodes:["SW19"], hub:"Affluent SME", industries:["Professional services","Hospitality","Retail","Tech"], tagline:"South-west London's affluent SME hub", intro:"Wimbledon's professional services firms, hospitality and retail businesses serve one of London's most affluent catchments. We deliver digital that converts that audience.", featured:false },
  { slug:'putney', name:"Putney", postcodes:["SW15"], hub:"Affluent SME, healthcare", industries:["Healthcare","Professional services","Hospitality","Property"], tagline:"SW15 commercial hub", intro:"Putney's mix of healthcare, professional services and lifestyle businesses serves a high-LTV catchment. We help them capture more of it.", featured:false },
  { slug:'clapham', name:"Clapham", postcodes:["SW4","SW11"], hub:"Lifestyle, hospitality", industries:["Hospitality","Retail","Wellness","Property"], tagline:"South London's lifestyle hub", intro:"Clapham's restaurants, gyms, hospitality and lifestyle brands need digital that matches their energy. We bring it.", featured:false },
  { slug:'brixton', name:"Brixton", postcodes:["SW2","SW9"], hub:"Creative, hospitality", industries:["Hospitality","Creative","Music","Retail"], tagline:"Distinctive South London brands", intro:"Brixton's distinctive cultural identity makes it one of London's most interesting commercial zones. We work with restaurants, bars, creative businesses and retailers that define it.", featured:false },
  { slug:'croydon', name:"Croydon", postcodes:["CR0","CR2"], hub:"Tech, business services", industries:["Tech","B2B","Property","Healthcare"], tagline:"South London business hub", intro:"Croydon's tech corridor and growing business services base offer the most cost-effective London commercial market. Lower competition for local SEO too — we exploit both.", featured:false },
  { slug:'richmond', name:"Richmond", postcodes:["TW9","TW10"], hub:"Affluent SME, hospitality", industries:["Hospitality","Professional services","Healthcare","Property"], tagline:"South-west London affluent hub", intro:"Richmond serves one of London's most affluent catchments. Premium positioning, taste-led digital marketing, and SEO that owns the local 3-pack.", featured:false },
  { slug:'kingston', name:"Kingston upon Thames", postcodes:["KT1","KT2"], hub:"Retail, education, hospitality", industries:["Retail","Education","Hospitality","Property"], tagline:"South-west London retail hub", intro:"Kingston's town-centre retail, university-driven economy and family-affluent catchment make it a distinctive London market. We deliver digital that converts it.", featured:false },
  { slug:'wandsworth', name:"Wandsworth", postcodes:["SW18"], hub:"Family, hospitality, property", industries:["Property","Hospitality","Retail","Healthcare"], tagline:"SW18 family commercial hub", intro:"Wandsworth's family-affluent catchment supports a strong local commercial base. We deliver digital that ranks for borough-level terms with high commercial intent.", featured:false },
  { slug:'lambeth', name:"Lambeth", postcodes:["SE1","SE11"], hub:"Hospitality, healthcare", industries:["Hospitality","Healthcare","Tourism","Cultural"], tagline:"South Bank to Vauxhall", intro:"Lambeth runs from South Bank's tourism economy through Waterloo's commuter hub to Vauxhall's growing residential. We deliver digital across all of it.", featured:false },
  { slug:'southwark', name:"Southwark", postcodes:["SE1"], hub:"Tech, media, hospitality", industries:["Tech","Media","Hospitality","B2B"], tagline:"Borough Market to More London", intro:"Southwark's tech businesses around More London, media in Bankside, and the hospitality economy of Borough Market all need digital that performs. We deliver.", featured:false },
  { slug:'bermondsey', name:"Bermondsey", postcodes:["SE1","SE16"], hub:"Creative, hospitality", industries:["Hospitality","Creative","Tech","Property"], tagline:"SE1's creative quarter", intro:"Bermondsey's creative businesses and hospitality scene need distinctive digital. We bring point-of-view that matches their craft.", featured:false },
  { slug:'lewisham', name:"Lewisham", postcodes:["SE13","SE14"], hub:"Local commerce", industries:["Retail","Hospitality","Healthcare","Education"], tagline:"South-east London local commerce", intro:"Lewisham's local businesses serve a fast-growing catchment. We deliver hyper-local SEO and paid that owns the 3-pack across SE13/14.", featured:false },
  { slug:'tower-hamlets', name:"Tower Hamlets", postcodes:["E1","E2","E14"], hub:"Tech, finance, lifestyle", industries:["Fintech","Tech","Hospitality","Property"], tagline:"East London's commercial spine", intro:"Tower Hamlets covers everything from Canary Wharf's finance to Brick Lane's hospitality to Whitechapel's tech scene. We work across all of it.", featured:false },
  { slug:'newham', name:"Newham", postcodes:["E15","E16","E20"], hub:"E-commerce, sport, tech", industries:["E-commerce","Sport","Tech","Hospitality"], tagline:"East London growth corridor", intro:"Newham's Olympic-anchored growth and Royal Docks tech corridor make it East London's most dynamic commercial zone. We support businesses building the next chapter.", featured:false },
  { slug:'waltham-forest', name:"Waltham Forest", postcodes:["E17"], hub:"Creative, lifestyle", industries:["Creative","Hospitality","Retail","Wellness"], tagline:"Walthamstow's creative scene", intro:"Waltham Forest's creative density and lifestyle business base need distinctive digital. We bring it.", featured:false },
  { slug:'haringey', name:"Haringey", postcodes:["N4","N15","N22"], hub:"Lifestyle, hospitality", industries:["Hospitality","Retail","Creative","Wellness"], tagline:"North London lifestyle hub", intro:"Haringey's mix of Crouch End, Tottenham and Wood Green serves a diverse commercial base. We deliver digital that works across it.", featured:false },
  { slug:'enfield', name:"Enfield", postcodes:["EN1","EN2"], hub:"Family, retail", industries:["Retail","Healthcare","Property","B2B"], tagline:"North London family commercial hub", intro:"Enfield's family-affluent catchment and growing town-centre regeneration make it a serious commercial zone. We deliver digital that owns local search.", featured:false },
  { slug:'barnet', name:"Barnet", postcodes:["N12","NW4"], hub:"Affluent family", industries:["Healthcare","Education","Retail","Property"], tagline:"North-west London family hub", intro:"Barnet's affluent family catchment supports a serious local commercial base. We deliver hyper-local SEO and paid that converts.", featured:false },
  { slug:'brent', name:"Brent", postcodes:["NW10","HA9"], hub:"Sport, retail, tech", industries:["Sport","Retail","Hospitality","Tech"], tagline:"Wembley to Park Royal", intro:"Brent runs from Wembley's sport and entertainment economy through Park Royal's industrial base. We deliver digital across both.", featured:false },
  { slug:'ealing', name:"Ealing", postcodes:["W5","W13"], hub:"Affluent SME", industries:["Professional services","Hospitality","Retail","Education"], tagline:"West London affluent suburb", intro:"Ealing's affluent catchment and town-centre regeneration support a strong commercial base. We deliver borough-level digital that performs.", featured:false },
  { slug:'hounslow', name:"Hounslow", postcodes:["TW3","TW7"], hub:"Heathrow corridor", industries:["B2B","Hospitality","Retail","Property"], tagline:"West London / Heathrow", intro:"Hounslow's Heathrow-anchored economy and town-centre commercial base need digital that converts. We deliver.", featured:false },
  { slug:'harrow', name:"Harrow", postcodes:["HA1","HA2"], hub:"Family, retail, healthcare", industries:["Healthcare","Retail","Property","Education"], tagline:"North-west London family hub", intro:"Harrow's affluent family catchment supports a strong local commercial base. We deliver hyper-local SEO and paid that owns it.", featured:false },
  { slug:'redbridge', name:"Redbridge", postcodes:["IG1","IG6"], hub:"Family, retail, healthcare", industries:["Healthcare","Retail","Property","B2B"], tagline:"North-east London family hub", intro:"Redbridge's family catchment and Ilford town-centre regeneration support a growing commercial base. We deliver digital that performs across it.", featured:false },
];

export const FEATURED_BOROUGHS = BOROUGHS.filter(b => b.featured);
export const ALL_BOROUGH_SLUGS = BOROUGHS.map(b => b.slug);

export function getBorough(slug: string): Borough | undefined {
  return BOROUGHS.find(b => b.slug === slug);
}
